In [3]:
#Task 1
age = input("Enter age:")
name = input("Enter name:")
print("Hello, my name is "+name+",and I am "+age+" years old.")

Enter age:20
Enter name:Deepak
Hello, my name is Deepak,and I am 20 years old.


In [4]:
#Task 2
str = "Datascience is used to extract meaningful insights."
print(str.split())
str = "Datascience\tis\tused\tto\textract\tmeaningful\tinsights"
print(str.split("\t"))
str = "Datascience\nis\nused\nto\nextract\nmeaningful\ninsights"
print(str.split('\n')) 
str = "Datascience is used to extract meaningful insights." 
print(str.split(",")) 

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']
['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights']
['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights']
['Datascience is used to extract meaningful insights.']


In [6]:
#Task 3
num_1 = input("Enter the first number")
num_2 = input("Enter the second number")
product = float(num_1) * float(num_2)
print("Product of {} and {} is {}".format(num_1, num_2,product))

Enter the first number69
Enter the second number50
Product of 69 and 50 is 3450.0


In [7]:
#Task 4
capital_city = {"Telangana": "Hyderabad", "Goa": "Panaji", "Odisha": "Bhubaneswar", "Arunachal Pradesh": "Itanagar", "Tamil Nadu": "Chennai"}
print(capital_city)

{'Telangana': 'Hyderabad', 'Goa': 'Panaji', 'Odisha': 'Bhubaneswar', 'Arunachal Pradesh': 'Itanagar', 'Tamil Nadu': 'Chennai'}


In [8]:
#Task 5
def createList(r1):
    res = []
    for i in range(r1):
        res.append(i)
    return res
r = 1000
print(createList(r))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [10]:
#Task 6
import numpy as np 
dimension = int(input("Enter the dimension of identity matrix:"))
identity_matrix = np.identity(dimension, dtype="int")
print(identity_matrix)

Enter the dimension of identity matrix:4
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [11]:
#Task 7
import numpy as np 
a = np.arange(1, 10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#Task 8
import numpy as np
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
result = a1 + a2
print(result)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [13]:
#Task 9
from datetime import datetime, timedelta
start_date = datetime(2023, 2, 1)
end_date = datetime(2023, 3, 1)
dates = []
current_date = start_date
while current_date <= end_date:
    dates.append(current_date.strftime('%Y-%m-%d'))
    current_date += timedelta(days=1)
for date in dates:
    print(date)

2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10
2023-02-11
2023-02-12
2023-02-13
2023-02-14
2023-02-15
2023-02-16
2023-02-17
2023-02-18
2023-02-19
2023-02-20
2023-02-21
2023-02-22
2023-02-23
2023-02-24
2023-02-25
2023-02-26
2023-02-27
2023-02-28
2023-03-01


In [15]:
#Task 10
import pandas as pd
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
df = pd.DataFrame(dictionary)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
